baseURL = "https://miyazawakai.com/"
languageCode = "ja"
title = "miyazawakai.com"
theme = "stack"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[params]
  mainSections = ["blog"]
  favicon = "favicon.jpg"
